Make the badge tool logos clickable like titles
GoogleChromeLabs/tooling.report pull request #354
Opened 2020-07-02 01:22 UTC by pajaydev

Fixes https://github.com/GoogleChromeLabs/tooling.report/issues/277

2020-07-02 01:23 UTC, pajaydev commented
@googlebot I signed it!

2020-07-02 17:28 UTC, argyleink requested changes
Hi @pajaydev, thanks for taking this on! 

This does cause a regression in shape, the images are no longer circles! 🙂 

<details>

<summary>screenshot</summary>

<img width="1044" alt="Screen Shot 2020-07-02 at 10 22 53 AM" src="https://user-images.githubusercontent.com/1134620/86391173-3754d980-bc4e-11ea-8f5e-ea3a7b7ab60b.png">

</details>

Looks like making the image a link has added padding and changed the box shape. I added `padding: 0;` to the `.toolIcon` class in this file `static-build/components/TestResultSnippet/styles.css` and it resolved the issue. Can you update this PR to remove the padding from toolIcons please 👍 Then I think this is g2g.

2020-07-02 20:38 UTC, pajaydev commented
@argyleink  Thanks 👍  I have reset the padding. Kindly review and check the below screenshot


<img width="1088" alt="Screen Shot 2020-07-02 at 1 33 24 PM" src="https://user-images.githubusercontent.com/21375014/86407068-2bc2dc00-bc69-11ea-9cd3-652c449336ae.png">

2020-07-03 22:36 UTC, surma commented
(@developit unrelated, any idea why the preview script isn’t running on this one?)

2020-07-04 03:42 UTC, developit commented
@surma I think it only runs on non-fork PRs, because it's not an official GH app.

2020-07-06 13:26 UTC, jakearchibald commented on static-build/components/TestResultSnippet/index.tsx
> +            alt={`${name} bundler logo`}
```suggestion
            alt={`${name}`}
```

2020-07-06 13:28 UTC, jakearchibald commented on static-build/components/TestResultSnippet/index.tsx
> +            alt={`${name} bundler logo`}
Minor tweak. In terms of accessibility the image is representing the build tool. It doesn't seem necessary to announce that it's the icon.

2020-07-06 13:28 UTC, jakearchibald commented
I'm happy if @argyleink & @una are happy.

2020-07-06 15:01 UTC, argyleink approved these changes

2020-07-06 15:18 UTC, merged

2020-07-06 15:19 UTC, jakearchibald commented
Thanks @pajaydev! This change will be on the live site shortly